# Generated by Django 2.1.3 on 2019-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190417_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
